services:
  kandb:
    image: postgres:alpine
    restart: always
    container_name: kandb
    environment:
      POSTGRES_USER: "kanuser"
      POSTGRES_DB: "kandb"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5432:5432
    volumes:
      - kandb-data:/var/lib/postgresql/data
      - ./backend/database/:/docker-entrypoint-initdb.d/
    networks:
      - kanban-net
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "log@me.in"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - kanban-net
    depends_on:
      - kandb

networks:
  kanban-net:
    name: kan-net

volumes:
  kandb-data:
  pgadmin-data:

    
    