services:
  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "log@me.in"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_:
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - kanban-net
    depends_on:
      - kandb
  
  kandb:
    image: postgres:alpine
    restart: always
    container_name: kandb
    environment:
      POSTGRES_USER: "kanuser"
      POSTGRES_DB: "kandb"
      POSTGRES_PASSWORD: "secret"
    ports:
      - 5432:5432
    volumes:
      - kandb-data:/var/lib/postgresql/data
      - ./backend/database/:/docker-entrypoint-initdb.d/
    networks:
      - kanban-net
  
  api:
    container_name: api_container
    build: ./backend/api
    restart: always
    environment:
      DATABASE_URL: postgresql://kanuser:secret@kandb:5432/kandb # Values from kandb, environment
    ports:
      - "3000:3000"
    depends_on:
      - kandb
    networks:
      - kanban-net



networks:
  kanban-net:
    name: kan-net
    

volumes:
  kandb-data:
  pgadmin-data:

    
    